/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description OAuth2 password flow: `username` is the admin's email.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cats */
        get: operations["list_cats_api_v1_cats_get"];
        put?: never;
        /** Create Cat */
        post: operations["create_cat_api_v1_cats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cats/{cat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cat */
        get: operations["get_cat_api_v1_cats__cat_id__get"];
        put?: never;
        post?: never;
        /** Delete Cat */
        delete: operations["delete_cat_api_v1_cats__cat_id__delete"];
        options?: never;
        head?: never;
        /** Update Cat */
        patch: operations["update_cat_api_v1_cats__cat_id__patch"];
        trace?: never;
    };
    "/api/v1/cats/{cat_id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_cats__cat_id__applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cats/{cat_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Photo */
        post: operations["upload_photo_api_v1_cats__cat_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cats/{cat_id}/sounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Sound */
        post: operations["upload_sound_api_v1_cats__cat_id__sounds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["delete_photo_api_v1_photos__photo_id__delete"];
        options?: never;
        head?: never;
        /** Update Photo */
        patch: operations["update_photo_api_v1_photos__photo_id__patch"];
        trace?: never;
    };
    "/api/v1/sounds/{sound_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Sound */
        delete: operations["delete_sound_api_v1_sounds__sound_id__delete"];
        options?: never;
        head?: never;
        /** Update Sound */
        patch: operations["update_sound_api_v1_sounds__sound_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminRead */
        AdminRead: {
            /** Email */
            email: string;
            /** Id */
            id: number;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Has Other Pets
             * @default false
             */
            has_other_pets: boolean;
            housing_type: components["schemas"]["HousingType"];
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Phone
             * @default
             */
            phone: string;
        };
        /** ApplicationPage */
        ApplicationPage: {
            /** Items */
            items: components["schemas"]["ApplicationRead"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /**
         * ApplicationRead
         * @description Admin view: full applicant details.
         */
        ApplicationRead: {
            cat: components["schemas"]["CatSummary"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Has Other Pets */
            has_other_pets: boolean;
            housing_type: components["schemas"]["HousingType"];
            /** Id */
            id: number;
            /** Message */
            message: string;
            /** Phone */
            phone: string;
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationReceipt
         * @description Public response: confirms receipt without echoing personal data.
         */
        ApplicationReceipt: {
            /** Cat Id */
            cat_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "new" | "approved" | "rejected";
        /** ApplicationStatusUpdate */
        ApplicationStatusUpdate: {
            status: components["schemas"]["ApplicationStatus"];
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_upload_photo_api_v1_cats__cat_id__photos_post */
        Body_upload_photo_api_v1_cats__cat_id__photos_post: {
            /** File */
            file: string;
        };
        /** Body_upload_sound_api_v1_cats__cat_id__sounds_post */
        Body_upload_sound_api_v1_cats__cat_id__sounds_post: {
            /** File */
            file: string;
        };
        /** CatCreate */
        CatCreate: {
            /** Age Months */
            age_months: number;
            /**
             * Breed
             * @default
             */
            breed: string;
            /**
             * Castrated
             * @default false
             */
            castrated: boolean;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Good With Cats
             * @default false
             */
            good_with_cats: boolean;
            /**
             * Good With Dogs
             * @default false
             */
            good_with_dogs: boolean;
            /**
             * Good With Kids
             * @default false
             */
            good_with_kids: boolean;
            /** Name */
            name: string;
            sex: components["schemas"]["Sex"];
            /** @default available */
            status: components["schemas"]["CatStatus"];
        };
        /** CatPage */
        CatPage: {
            /** Items */
            items: components["schemas"]["CatRead"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** CatRead */
        CatRead: {
            /** Age Months */
            age_months: number;
            /** Breed */
            breed: string;
            /** Castrated */
            castrated: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Good With Cats */
            good_with_cats: boolean;
            /** Good With Dogs */
            good_with_dogs: boolean;
            /** Good With Kids */
            good_with_kids: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Photos
             * @default []
             */
            photos: components["schemas"]["PhotoRead"][];
            /** Primary Photo Url */
            readonly primary_photo_url: string | null;
            /** Primary Sound Url */
            readonly primary_sound_url: string;
            sex: components["schemas"]["Sex"];
            /**
             * Sounds
             * @default []
             */
            sounds: components["schemas"]["SoundRead"][];
            status: components["schemas"]["CatStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CatStatus
         * @enum {string}
         */
        CatStatus: "available" | "pending" | "adopted";
        /** CatSummary */
        CatSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            status: components["schemas"]["CatStatus"];
        };
        /**
         * CatUpdate
         * @description PATCH body: only the fields sent are changed (exclude_unset).
         *     Sending null is rejected, so a required field can't be cleared.
         */
        CatUpdate: {
            /** Age Months */
            age_months?: number | null;
            /** Breed */
            breed?: string | null;
            /** Castrated */
            castrated?: boolean | null;
            /** Description */
            description?: string | null;
            /** Good With Cats */
            good_with_cats?: boolean | null;
            /** Good With Dogs */
            good_with_dogs?: boolean | null;
            /** Good With Kids */
            good_with_kids?: boolean | null;
            /** Name */
            name?: string | null;
            sex?: components["schemas"]["Sex"] | null;
            status?: components["schemas"]["CatStatus"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HousingType
         * @enum {string}
         */
        HousingType: "apartment" | "house" | "house_with_garden";
        /** MediaUpdate */
        MediaUpdate: {
            /**
             * Is Primary
             * @constant
             */
            is_primary: true;
        };
        /** PhotoRead */
        PhotoRead: {
            /** Height */
            height: number;
            /** Id */
            id: number;
            /** Is Primary */
            is_primary: boolean;
            /** Url */
            readonly url: string;
            /** Width */
            width: number;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female";
        /** SoundRead */
        SoundRead: {
            /** Content Type */
            content_type: string;
            /** Duration S */
            duration_s: number | null;
            /** Id */
            id: number;
            /** Is Primary */
            is_primary: boolean;
            /** Url */
            readonly url: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                cat_id?: number | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Transition not allowed or cat already adopted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRead"];
                };
            };
        };
    };
    list_cats_api_v1_cats_get: {
        parameters: {
            query?: {
                sex?: components["schemas"]["Sex"] | null;
                castrated?: boolean | null;
                status?: components["schemas"]["CatStatus"] | null;
                breed?: string | null;
                good_with_kids?: boolean | null;
                good_with_cats?: boolean | null;
                good_with_dogs?: boolean | null;
                min_age_months?: number | null;
                max_age_months?: number | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cat_api_v1_cats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cat_api_v1_cats__cat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cat_api_v1_cats__cat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cat_api_v1_cats__cat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_cats__cat_id__applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationReceipt"];
                };
            };
            /** @description Cat not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cat adopted or duplicate */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_v1_cats__cat_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_v1_cats__cat_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_sound_api_v1_cats__cat_id__sounds_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_sound_api_v1_cats__cat_id__sounds_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_v1_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_photo_api_v1_photos__photo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sound_api_v1_sounds__sound_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sound_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sound_api_v1_sounds__sound_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sound_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
