"""create applications table

Revision ID: 7de78bf50d28
Revises: c213b1360b7e
Create Date: 2026-09-29 08:24:25.653379
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7de78bf50d28'
down_revision: str | None = 'c213b1360b7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('housing_type', sa.Enum('apartment', 'house', 'house_with_garden', name='housingtype', native_enum=False, length=20), nullable=False),
    sa.Column('has_other_pets', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'approved', 'rejected', name='applicationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name=op.f('fk_applications_cat_id_cats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('cat_id', 'email', name=op.f('uq_applications_cat_id_email'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))

    op.drop_table('applications')
    # ### end Alembic commands ###
