"""create login_failures table

Revision ID: b21670e6490d
Revises: d4da6eef9fc3
Create Date: 2026-09-29 12:56:49.288500
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b21670e6490d'
down_revision: str | None = 'd4da6eef9fc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_failures'))
    )
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_failures_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_login_failures_ip_created_at', ['ip', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.drop_index('ix_login_failures_ip_created_at')
        batch_op.drop_index(batch_op.f('ix_login_failures_created_at'))

    op.drop_table('login_failures')
    # ### end Alembic commands ###
