"""create cats table

Revision ID: c213b1360b7e
Revises: 
Create Date: 2026-09-28 11:46:29.672777
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c213b1360b7e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex', native_enum=False, length=20), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('castrated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('available', 'pending', 'adopted', name='catstatus', native_enum=False, length=20), nullable=False),
    sa.Column('good_with_kids', sa.Boolean(), nullable=False),
    sa.Column('good_with_cats', sa.Boolean(), nullable=False),
    sa.Column('good_with_dogs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cats_castrated'), ['castrated'], unique=False)
        batch_op.create_index(batch_op.f('ix_cats_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cats_status'))
        batch_op.drop_index(batch_op.f('ix_cats_castrated'))

    op.drop_table('cats')
    # ### end Alembic commands ###
