"""create cat photos and sounds tables

Revision ID: d4da6eef9fc3
Revises: d5853b6cb3fb
Create Date: 2026-09-29 10:14:17.426408
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd4da6eef9fc3'
down_revision: str | None = 'd5853b6cb3fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Partial unique indexes (one primary per cat). The WHERE clause is written
    # per dialect: Postgres rejects comparing a boolean with 1.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_photos',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name=op.f('fk_cat_photos_cat_id_cats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_photos'))
    )
    with op.batch_alter_table('cat_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_photos_cat_id'), ['cat_id'], unique=False)
        batch_op.create_index('uq_cat_photos_one_primary', ['cat_id'], unique=True, sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))

    op.create_table('cat_sounds',
    sa.Column('duration_s', sa.Double(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name=op.f('fk_cat_sounds_cat_id_cats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_sounds'))
    )
    with op.batch_alter_table('cat_sounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_sounds_cat_id'), ['cat_id'], unique=False)
        batch_op.create_index('uq_cat_sounds_one_primary', ['cat_id'], unique=True, sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_sounds', schema=None) as batch_op:
        batch_op.drop_index('uq_cat_sounds_one_primary', sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))
        batch_op.drop_index(batch_op.f('ix_cat_sounds_cat_id'))

    op.drop_table('cat_sounds')
    with op.batch_alter_table('cat_photos', schema=None) as batch_op:
        batch_op.drop_index('uq_cat_photos_one_primary', sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))
        batch_op.drop_index(batch_op.f('ix_cat_photos_cat_id'))

    op.drop_table('cat_photos')
    # ### end Alembic commands ###
